[WIP] YCDOCIO-2543: Remake DataProc to CH tutorial
yandex-cloud/examples pull request #190
Opened 2023-04-25 19:47 UTC by makushevkm-doctat

Remake DataProc to CH tutorial

2023-04-27 05:19 UTC, voloschuk-fedor requested changes

2023-04-27 07:44 UTC, makushevkm-doctat commented on tutorials/terraform/data-proc-data-exchange-with-mch.tf
> +  # Change the following settings only if necessary
Ок, но это двоеточие :)

2023-04-27 08:04 UTC, makushevkm-doctat commented on tutorials/terraform/data-proc-data-exchange-with-mch.tf
> +  # Change the following settings only if necessary
Ок, но мне кажется что среднее предложение избыточное. Давай напишем так:

# The following settings are predefined. Change them only if necessary.

2023-04-27 08:05 UTC, makushevkm-doctat commented on tutorials/terraform/data-proc-data-exchange-with-mch.tf
> +  # Change the following settings only if necessary
Поскольку теперь я написал так: 
`# The following settings are predefined. Change them only if necessary.`,
кажется, что двоеточие не нужно, т. к. последнее предложение не является вводным к списку.

2023-05-02 04:11 UTC, voloschuk-fedor commented on tutorials/terraform/data-proc-data-exchange-with-mch.tf
> +  # Change the following settings only if necessary
Отличный вариант!

2023-05-02 04:12 UTC, voloschuk-fedor commented on tutorials/terraform/data-proc-data-exchange-with-mch.tf
> +  # Change the following settings only if necessary
Да, отлично!

2023-05-02 04:12 UTC, voloschuk-fedor approved these changes

2023-05-29 12:29 UTC, lanieuszko approved these changes

2023-05-29 12:30 UTC, merged