[WIP] YCDOCIO-2943: add TF files for k8s-fluent-bit-and-master-loggin
yandex-cloud/examples pull request #213
Opened 2023-09-08 12:45 UTC by AnatolyKraev

https://st.yandex-team.ru/YCDOCIO-2943

add TF files for k8s-fluent-bit-and-master-loggin

2023-09-18 16:07 UTC, alena-linki requested changes
Первое внутреннее ревью

2023-09-18 16:07 UTC, alena-linki commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +    description    = "The rule allows connection to Kubernetes API on 443 port from specified network"
on port 443 from the specified network

2023-09-18 16:07 UTC, alena-linki commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +  description = "Security group allows connections to services from the internet. Apply the rules only for node groups."
```suggestion
  description = "The security group allows connections to services from the internet. Apply the rules only for your node groups."
```

2023-09-18 16:07 UTC, alena-linki commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +  description = "Service account for Kubernetes cluster"
```suggestion
  description = "Service account for the Kubernetes cluster"
```

2023-09-18 16:07 UTC, alena-linki commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +# Assign "editor" role to Kubernetes service account
Либо
```suggestion
# Assign role "editor" to the Kubernetes service account
```

Либо
```suggestion
# Assign the editor role to the Kubernetes service account
```

Справедливо здесь и далее

2023-09-18 16:07 UTC, alena-linki commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +  service_account_id      = yandex_iam_service_account.k8s-sa.id # Cluster service account ID
Здесь и ниже слишком много существительных подряд, тяжело разбирать такие формулировки. Давай в обоих местах поменяем порядок слов:

ID of the service account for the cluster
ID of the service account for the node group

2023-09-18 16:07 UTC, alena-linki commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +  description = "Node group for Managed Service for Kubernetes cluster"
```suggestion
  description = "Node group for the Managed Service for Kubernetes cluster"
```

2023-09-18 16:07 UTC, alena-linki commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-log-group.tf
Просьба учесть те же комментарии и идеи, что для соседнего файла

2023-09-19 09:42 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +  folder_id      = "" # Your cloud folder ID, same as for provider
Да, нужно указать, мы назначаем роль на каталог или облаков. Соответственно указываем ID каталога или облака.

2023-09-19 09:44 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +  description    = "Subnet in ru-central1-a availability zone"
Ок

2023-09-19 09:48 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +  description = "Security group ensure the basic performance of the cluster. Apply it to the cluster and node groups."
Ок

2023-09-19 09:52 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +    description    = "The rule allows the pod-pod and service-service interaction. Specify the subnets of your cluster and services."
Блин, ну ты валишь совсем, это Федя писал, Костя вроде проверял, я вообще хз))) но кажется ты права)
Я так понял все эти правила взяты из https://cloud.yandex.ru/docs/managed-kubernetes/operations/connect/security-groups#rules-internal а описания Федя сам придумывал на английском.

2023-09-19 09:53 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +    description    = "The rule allows receipt of debugging ICMP packets from internal subnets"
Ок

2023-09-19 09:53 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +    description    = "The rule allows connection to Kubernetes API on 6443 port from specified network"
Ок

2023-09-19 09:54 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +  description = "Security group allows connections to services from the internet. Apply the rules only for node groups."
Ок

2023-09-19 09:56 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +  description = "Service account for Kubernetes cluster"
Ок

2023-09-19 09:59 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +# Assign "editor" role to Kubernetes service account
Ок

2023-09-19 09:59 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +  service_account_id      = yandex_iam_service_account.k8s-sa.id # Cluster service account ID
Ок

2023-09-19 10:00 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +  description = "Node group for Managed Service for Kubernetes cluster"
Ок

2023-09-19 10:00 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-log-group.tf
Ок

2023-09-20 07:19 UTC, alena-linki commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +  folder_id      = "" # Your cloud folder ID, same as for provider
понятно, спасибо!

2023-09-20 07:34 UTC, alena-linki commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +    description    = "The rule allows incoming traffic from the internet to the NodePort port range. Add ports or change existing ones to the required ports."
Даже после обсуждения в личке я все равно не понимаю, зачем менять порты, т. е. когда это может понадобиться. В [документации](https://server-yfm.website.yandexcloud.net/server-yfm-anatolykraev-YCDOCIO-2943-upd-k8s-fluent-bit-logging/ru/ru/managed-kubernetes/operations/connect/security-groups.html) не говорится, что этот диапазон надо менять. Но предполагаю, что здесь закопана какая-то глубокая мысль, которую я не улавливаю. Поэтому давай отделаемся малой кровью:

```suggestion
    description    = "The rule allows incoming traffic from the internet to the NodePort port range. Add ports or change the specified ports to the required ones."
```

2023-09-20 07:36 UTC, alena-linki commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +    description    = "The rule allows connection to Kubernetes API on 443 port from specified network"
Пока что не исправлено

2023-09-20 12:41 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +    description    = "The rule allows incoming traffic from the internet to the NodePort port range. Add ports or change existing ones to the required ports."
Ок, убрал совсем, потом уточним когда стайлгайд править будем, но мне очень кажется, что это лишнее.

2023-09-20 12:42 UTC, AnatolyKraev commented on tutorials/terraform/managed-kubernetes/k8s-cluster-with-master-logging.tf
> +    description    = "The rule allows connection to Kubernetes API on 443 port from specified network"
Ок

2023-09-20 13:24 UTC, alena-linki approved these changes

2023-11-23 10:10 UTC, vnkiryushkin approved these changes

2023-11-23 10:10 UTC, merged