[WIP] YCDOCIO-3078 Terraform configuration for Data Proc cluster DNS
yandex-cloud/examples pull request #223
Opened 2023-10-31 12:35 UTC by mikhaildoc-documentat

2023-11-02 04:09 UTC, voloschuk-fedor requested changes

2023-11-02 04:09 UTC, voloschuk-fedor commented on tutorials/terraform/data-proc-dns-connect.tf
> +  dataproc_fqdn = "test" # Substitute "test" with the Data Proc master node FQDN
Этот параметр можно сразу задавать?

Я к тому, что при первом запуске у пользователя получится DNS-запись с именем test — это норма?

Может быть, этот параметр сначала закомментарить, и попросить открыть только на втором шаге?

2023-11-02 04:09 UTC, voloschuk-fedor commented on tutorials/terraform/data-proc-dns-connect.tf
> +  dataproc_fqdn = "test" # Substitute "test" with the Data Proc master node FQDN
Не исключаю, что при замене test на настоящий FQDN запись обновится, и всё будет ок.

2023-11-03 08:56 UTC, mikhaildoc-documentat commented on tutorials/terraform/data-proc-dns-connect.tf
> +  dataproc_fqdn = "test" # Substitute "test" with the Data Proc master node FQDN
Можно спокойно назначать `test` записи, потом изменить - важно, чтобы она была непустой

2023-11-07 03:52 UTC, voloschuk-fedor approved these changes

2023-11-17 13:30 UTC, lanieuszko approved these changes

2023-11-17 13:31 UTC, merged