YCDOCIO-3558: Updated Terraform manifests
yandex-cloud/examples pull request #255
Opened 2024-04-24 19:58 UTC by Nadezhda-Subotka

https://st.yandex-team.ru/YCDOCIO-3558

Updated Terraform manifests.

2024-04-27 07:42 UTC, voloschuk-fedor requested changes

2024-04-27 07:42 UTC, voloschuk-fedor commented on tutorials/terraform/sqoop/clusters-mysql-data-proc-and-vm.tf
> +# Database of the Managed Service for MySQL cluster
В этом PR тоже предлагаю написать так (после консультации с Алёной):

```suggestion
# Database for the Managed Service for MySQL cluster
```

2024-04-27 14:47 UTC, alena-linki commented on tutorials/terraform/sqoop/clusters-mysql-data-proc-and-vm.tf
> +# Database of the Managed Service for MySQL cluster
@Nadezhda-Subotka @voloschuk-fedor Давайте оставим of. Во-первых, Надя правильно отметила в тикете, что это написано по стайлгайду. Во-вторых, посмотрела по репозиторию — в большинстве случаев используется предлог "of". Предлог "for" ни разу не использовался.

Но с точки зрения английского тут можно и "of", и "for", и "in".

2024-04-27 15:11 UTC, alena-linki requested changes
Ревью англ. текстов

2024-04-27 15:11 UTC, alena-linki commented on tutorials/terraform/sqoop/clusters-mysql-data-proc-and-vm.tf
> +  my_cluster_username = "user1" # Set a database owner name
```suggestion
  my_cluster_username = "user1" # Database owner's name
```

Надо добавить 's, чтобы показать принадлежность. Кроме того, owner — это предмет одушевленный. Применимо здесь и во втором файле.

2024-04-27 15:11 UTC, alena-linki commented on tutorials/terraform/sqoop/clusters-mysql-data-proc-and-vm.tf
> +  my_cluster_password = ""      # Set a database owner password
```suggestion
  my_cluster_password = ""      # Database owner's password
```

2024-04-27 15:11 UTC, alena-linki commented on tutorials/terraform/sqoop/clusters-mysql-data-proc-and-vm.tf
>    vm_username         = ""      # Set a username for VM. Images with Ubuntu Linux use the username `ubuntu` by default.
```suggestion
  vm_username         = ""      # Set a username for VM. Images with Ubuntu Linux use the `ubuntu` username by default.
```

Ниже в подписи ресурсов используется именно такая последовательность. Давай везде сделаем одинаково. Применимо здесь и во втором файле.

2024-04-27 15:11 UTC, alena-linki commented on tutorials/terraform/sqoop/clusters-mysql-data-proc-and-vm.tf
> +    ssh-keys = "${local.vm_username}:${file(local.vm_public_key)}" # Username and SSH public key full path
```suggestion
    ssh-keys = "${local.vm_username}:${file(local.vm_public_key)}" # Username and the SSH public key full path
```

2024-04-27 15:11 UTC, alena-linki commented on tutorials/terraform/sqoop/clusters-mysql-data-proc-and-vm.tf
>    description        = "Object Storage bucket static key"
```suggestion
  description        = "Static key for the Object Storage bucket"
```

2024-04-27 15:11 UTC, alena-linki commented on tutorials/terraform/sqoop/clusters-postgresql-data-proc-and-vm.tf
> +# Security groups for the Managed Service for PostgreSQL cluster, Data Proc cluster, and VM
Если что, вот эта подпись необязательна. Обычно даем описание ресурса в поле `description`. Если такое поле не поддержано в ресурсе, то уже даем комментарий, как этот. А оба таких комментария избыточны. См. пункт 2 в разделе [Общие правила](https://github.com/documentat/ya-cloud-internal/blob/master/guides/terraform-manifest-styleguide.md#1-общие-правила-).

Применимо здесь и в других местах.

2024-05-13 13:54 UTC, Nadezhda-Subotka commented on tutorials/terraform/sqoop/clusters-mysql-data-proc-and-vm.tf
> +# EN: https://cloud.yandex.ru/en/docs/managed-mysql/tutorials/sqoop
Заменила ссылки.

2024-05-13 14:07 UTC, Nadezhda-Subotka commented on tutorials/terraform/sqoop/clusters-mysql-data-proc-and-vm.tf
> +  my_cluster_version  = "8.0"   # Set the MySQL® version: 5.7 or 8.0
> Кстати, пока писала последний пункт, поняла, что слова "set" вообще можно убрать. 

Не знаю почему, но в большинстве манифестов используется слово "set" в блоке, где пользователю самому нужно  указывать значения. Мне больше нравится без "set". Убрала его.

2024-05-13 14:08 UTC, Nadezhda-Subotka commented on tutorials/terraform/sqoop/clusters-mysql-data-proc-and-vm.tf
> +  my_cluster_username = "user1" # Set a database owner name
Исправила.

2024-05-13 14:12 UTC, Nadezhda-Subotka commented on tutorials/terraform/sqoop/clusters-mysql-data-proc-and-vm.tf
> +    ssh-keys = "${local.vm_username}:${file(local.vm_public_key)}" # Username and SSH public key full path
Исправила.

2024-05-13 14:13 UTC, Nadezhda-Subotka commented on tutorials/terraform/sqoop/clusters-mysql-data-proc-and-vm.tf
>    description        = "Object Storage bucket static key"
Исправила.

2024-05-13 14:17 UTC, Nadezhda-Subotka commented on tutorials/terraform/sqoop/clusters-postgresql-data-proc-and-vm.tf
> +# Security groups for the Managed Service for PostgreSQL cluster, Data Proc cluster, and VM
Спасибо, про правило я знаю. Только здесь этот комментарий выступает в роли подзаголовка. Я добавляла их, чтобы визуально отделить описание ресурсов от блока переменных. Предлагаю оставить.

2024-05-16 08:12 UTC, alena-linki commented on tutorials/terraform/sqoop/clusters-postgresql-data-proc-and-vm.tf
> +# Security groups for the Managed Service for PostgreSQL cluster, Data Proc cluster, and VM
Настаивать не буду, на твое усмотрение. Но идея, что это заголовок, не считывается. В глаза бросается в первую очередь дублирование описания. Также не понимаю, зачем как-то отделять ресурсы от блока переменных: по самому манифесту и так понятно, где ресурсы, а где переменные.

2024-05-16 08:14 UTC, alena-linki approved these changes

2024-05-16 08:57 UTC, Nadezhda-Subotka commented on tutorials/terraform/sqoop/clusters-postgresql-data-proc-and-vm.tf
> +# Security groups for the Managed Service for PostgreSQL cluster, Data Proc cluster, and VM
Возможно, это субъективное, но мне удобнее ориентироваться в файле, когда есть заголовки, а не все сплошной простыней. Оставлю как есть.

2024-05-23 11:39 UTC, merged