Terraform configs for Managed Service for ClickHouse hybrid storage tutorial
yandex-cloud/examples pull request #72
Opened 2022-03-15 18:10 UTC by maxdunaevsky-documentatio

Привет!

Это прототипы конфигурационных файлов, которые будут использоваться в [статье про гибридное хранилище в кластерах Managed Service for ClickHouse](https://cloud.yandex.ru/docs/managed-clickhouse/tutorials/hybrid-storage).

Подробности в задаче [YCDOCIO-1308](https://st.yandex-team.ru/YCDOCIO-1308).

2022-03-23 11:34 UTC, a-chegodaev requested changes

2022-03-23 11:34 UTC, a-chegodaev commented on tutorials/terraform/clickhouse-hybrid-storage.tf
> +    password = "" # Set the user password
```suggestion
    name     = "" # Set username
    password = "" # Set user password
```

2022-03-23 11:34 UTC, a-chegodaev commented on tutorials/terraform/clickhouse-hybrid-storage.tf
> +# Infrastructure for Yandex.Cloud Managed Service for ClickHouse cluster with hybrid storage
```suggestion
# Infrastructure for Yandex Cloud Managed Service for ClickHouse cluster with hybrid storage
```

2022-03-23 11:34 UTC, a-chegodaev commented on tutorials/terraform/README.md
> +# Terraform configuration files for Yandex.Cloud practical guides
```suggestion
# Terraform configuration files for Yandex Cloud practical guides
```

2022-03-23 19:49 UTC, maxdunaevsky-documentatio commented on tutorials/terraform/clickhouse-hybrid-storage.tf
> +    password = "" # Set the user password
Исправлено.

2022-03-23 19:51 UTC, maxdunaevsky-documentatio commented on tutorials/terraform/clickhouse-hybrid-storage.tf
> +# Infrastructure for Yandex.Cloud Managed Service for ClickHouse cluster with hybrid storage
Исправил везде.

2022-03-23 19:51 UTC, maxdunaevsky-documentatio commented on tutorials/terraform/README.md
> +# Terraform configuration files for Yandex.Cloud practical guides
Исправил везде.

2022-03-23 19:54 UTC, maxdunaevsky-documentatio commented
@a-chegodaev , привет! Сделай ещё одно ревью, пожалуйста.

2022-03-29 08:16 UTC, a-chegodaev approved these changes

2022-03-29 08:17 UTC, merged